spring:
  application:
    name: user-auth-api

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.110.46:8848
        username: nacos
        password: nacos
        namespace: 44ad37b3-3947-4af3-8f6a-1b6189a46c1c
        group: shoplook

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoplook2025?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

server:
  port: 9001

jwt:
  secret: BqRg2WxlhDo4kD9KZIydB6yVtUbbC8wjnvCyBoRpIGI8A/LEaHbOGMkh7t3fN5g/